name: Ping Render App

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Call Render App
        run: |
          curl -s --retry 3 --fail https://hospital-booking-4s8o.onrender.com/health || echo "Ping failed"
